FROM node:22-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY tailwind.config.js .
COPY postcss.config.js .

RUN npm ci

RUN npx browserslist@latest --update-db

EXPOSE 3000

CMD ["npm", "run", "start"]